### ISSUE TITLE
Pyxiewps ends unexpectedly during APs enumerating.

### ISSUE THREAD

**Issue by ghost** [jgilhutton/pyxiewps#4]
The script ends unexpectedly while running in WALK mode. An python error is printed at end of script, please find the output below.

Setup: Kali Linux x64
Wifi adapter: Alfa AWUS036H - 54mb (b/g)
ETSI enviroment.

Not sure what else I can add,
Best regard,

Error msg:

```
root@K:/pyxiewps-master#python pyxiewps-EN.py --mode WALK

**********************************************************************
[+] Enumerating WPS-active APs...


[!] No WPS-active APs were found.

[+] Enumerating WPS-active APs...
[+] The following WPS-active APs were found:
    [>] NEUF_XXXX || 00:25:15:XX:XX:XX || Channel: 01 || RSSI: -69 || WPS: 1.0
    [>] NEUF_XXXX || 00:25:15:XX:XX:XX || Channel: 01 || RSSI: -72 || WPS: 1.0
[+] Fetching information from NEUF_XXXX using reaver...

[!] Couldn't retrieve any information from the AP.
[!] Try with a greater time using the -t argument
    and if it doesn't work out try to get a better signal.

**********************************************************************

[+] Fetching information from NEUF_XXXX using reaver...

[!] Couldn't retrieve any information from the AP.
[!] Try with a greater time using the -t argument
    and if it doesn't work out try to get a better signal.

**********************************************************************

[+] Enumerating WPS-active APs...
Traceback (most recent call last):
  File "pyxiewps-EN.py", line 983, in <module>
    engine.check()
  File "pyxiewps-EN.py", line 476, in check
    engine.start()
  File "pyxiewps-EN.py", line 274, in start
    attack.get_wps_aps()
  File "pyxiewps-EN.py", line 778, in get_wps_aps
    ap_list = engine.parse_airodump(output)
  File "pyxiewps-EN.py", line 376, in parse_airodump
    wps = snowden[0:snowden.index('  ')].strip()
ValueError: substring not found
root@K:/home/pixie/pyxiewps-master# 
```

**Comment by jgilhutton** [comment]
Oh shit.... Airodump again. I thought that this error was fixed but here you are with it hahaha.
Something that would be awesome is that you run Airodump separately and post a screencap so I can see where the problem is and the leght of the lines (You can hide any Mac and essid name if you want).
For you to understand (I don't want to insult you, I just don't know what you know :) ) this script heavyly depends on the lenght of the airodump's output lines (give it a read to the parse_airodump() ufnction). I spend 2 days writting this function and, as you can see, still gives me the hell of headaches.
I will try to fix this error, or change the entire function, asap.
Meanwhile, try to post a screencap of the output from Airodump
Juan Ignacio

**Comment by jgilhutton** [comment]
Can not find some other way to parse Airodump. Seems that the best option is to go around the problem and skip those Airodump entries with problems.
Not a solution, but will do:
https://github.com/jgilhutton/pyxiewps/commit/2b85227d9fc5b9defdbd442905e5eef259243c96

**Comment by ghost** [comment]
Hey Juan,

After the error showed up in Pyxiewps, I launched a default scan with airodump-ng and the errors seems to be this character. It's French characters, the prime/apostrophe character is not properly printed in airodump-ng, could this be the problem?

I haven't tried the latest version yet which contains your latest commit 2b85227.

Screenshot of error:

![pyxiewps_airodump_parse_error_1](https://cloud.githubusercontent.com/assets/10058545/8903194/58a6c380-3456-11e5-8379-2d3a7457d2e1.gif)

**Comment by jgilhutton** [comment]
New update.... hope it works now.
I'm sorry for wasting your time.
Juan
